### PR TITLE
Bump Elixir/Erlang versions in CI

### PR DESCRIPTION
**Pull request by kianmeng**
## 📖 Description and reason

Ensure support of the library for latest Elixir/Erlang versions.

#### Tasks

- [x] Bump Elixir/Erlang version in GitHub Action config.
- [x] Bump Credo and Excoveralls to make it works with all Elixir/Erlang versions.
- [x] Bump project minimum Elixir requirement to 1.8. 
- [x] Regenerate and update `.credo.exs`.
- [x] Update GitHub Action CI to run on `master` branch.

## 🦀 Dispatch

`#dispatch/elixir`

### CODE REVIEW

**Comment by kianmeng** [comment]
Note that it won't work with Erlang/OTP 26:

```sh
Compiling 56 files (.ex)
warning: atom ::: must be written between quotes, as in :"::", to avoid ambiguity
  lib/ecto/query/builder.ex:246:8


== Compilation error in file lib/ecto/query.ex ==
** (CompileError) lib/ecto/query.ex:427: type dynamic/0 is a built-in type and it cannot be redefined
    (elixir 1.14.5) lib/kernel/typespec.ex:936: Kernel.Typespec.compile_error/2
    (stdlib 5.0.1) lists.erl:1599: :lists.foldl_1/3
    (elixir 1.14.5) lib/kernel/typespec.ex:226: Kernel.Typespec.translate_typespecs_for_module/2
could not compile dependency :ecto, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ecto", update it with "mix deps.update ecto" or clean it with "mix deps.clean ecto"
```

**Comment by remi** [comment]
I don’t know why the CI builds didn’t run in this PR… I’m working on bringing support for Elixir 1.16 and 1.17 so we’ll be able to close this one 🙂

**Comment by kianmeng** [comment]
Superseded by https://github.com/mirego/absinthe_error_payload/pull/37

**Comment by remi** [comment]
@kianmeng Version 1.2.0 has been released with support for newer OTP/Elixir versions.
